services:
  db:
    image: mongo:7
    container_name: db
    command:
      - --storageEngine=wiredTiger
    logging:
      driver: none
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - 'db_data:/data/db'
  minio:
    image: 'quay.io/minio/minio:latest'
    container_name: minio
    command: 'server /data --console-address ":9001"'
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - 'minio_data:/data'

volumes:
  db_data:
  minio_data:
